services:
  backend:
    build: .
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
